# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

url: "https://maureen-page.github.io"
baseurl: ""

# Name of website
title: Maureen L. Page

# Short description of your site
description: Bee biology, pollination ecology, conservation biology

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Home: ""
  About: "Bio"
  Research: "Research"
  Publications: "pubs"
  CV: "CV"
  Collaborators:
    - John Mola: "http://johnmola.com"
  More:
    - Williams Lab: "http://williamslab.ucdavis.edu"
  

avatar: "/img/Academic-Headshot copy.png"

# --- Background colour/image options --- #

navbar-col: "blue" 
# navbar-img: "/img/bgimage.png"
# footer-col: "blue"
# footer-img: "/img/bgimage.png"
# page-col: "#FF0000"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
author:
  name: Maureen L. Page
  email: "mpage@ucdavis.edu"
  github: maureenpage    # eg. daattali
  twitter: _MaureenPage


# Select which links to show in the footer
footer-links-active:
  email: true
  twitter: true
  github: false
  linkedin: false
  stackoverflow: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

# How to display the link to the website in the footer
url-pretty: "maureen.page"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #


plugins:
  - jekyll-seo-tag

# Fill in your Google Analytics ID to track your website using GA
# google_analytics: "UA-107912354-1" # un hashtag later to use this if you want 

# Google Tag Manager ID
#gtm: ""


# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 3

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  
